<?php
/**
 * Created by Anton Repin.
 * Date: 1/29/16
 * Time: 10:53 AM
 */
require("XMLParser.php");
$xmlParser = new \Xdio\XMLParser();
$xmlParser->setMaxIndexDepth(0);
$xmlParser->requireToIndexNodeName('order');

$string = '<?xml version="1.0" encoding="UTF-8"?>
<ns2:list xmlns:ns2="http://walmart.com/mp/orders" xmlns:ns3="http://walmart.com/">
   <ns2:meta>
      <ns2:totalCount>2319</ns2:totalCount>
      <ns2:limit>2</ns2:limit>
      <ns2:nextCursor>?limit=2&hasMoreElements=true&soIndex=2&poIndex=0&partnerId=255045&sellerId=3&status=Created&createdStartDate=2015-01-01&createdEndDate=2015-10-16T19:10:15.664Z</ns2:nextCursor>
   </ns2:meta>
   <ns2:elements>
      <ns2:order>
         <ns2:purchaseOrderId>1000018780</ns2:purchaseOrderId>
         <ns2:customerOrderId>5591500401192</ns2:customerOrderId>
         <ns2:customerEmailId>aml_hold1@walamrtlabs.com</ns2:customerEmailId>
         <ns2:orderDate>2015-10-16T16:32:31.000Z</ns2:orderDate>
         <ns2:shippingInfo>
            <ns2:phone>(408) 123-4567</ns2:phone>
            <ns2:estimatedDeliveryDate>2015-10-17T06:59:59.000Z</ns2:estimatedDeliveryDate>
            <ns2:methodCode>Standard</ns2:methodCode>
            <ns2:postalAddress>
               <ns2:name>AML TEST</ns2:name>
               <ns2:address1>Elm ave</ns2:address1>
               <ns2:city>San Bruno</ns2:city>
               <ns2:state>CA</ns2:state>
               <ns2:postalCode>94066</ns2:postalCode>
               <ns2:country>USA</ns2:country>
               <ns2:addressType>RESIDENTIAL</ns2:addressType>
            </ns2:postalAddress>
         </ns2:shippingInfo>
         <ns2:orderLines>
            <ns2:orderLine>
               <ns2:lineNumber>1</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
            <ns2:orderLine>
               <ns2:lineNumber>2</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
            <ns2:orderLine>
               <ns2:lineNumber>3</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
            <ns2:orderLine>
               <ns2:lineNumber>4</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
            <ns2:orderLine>
               <ns2:lineNumber>5</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                 <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
            <ns2:orderLine>
               <ns2:lineNumber>6</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>Pelican Monaco Deluxe Four Person Pedal Boat with White Deck and Blue Hull with Canopy</ns2:productName>
                  <ns2:sku>PEL1116</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>845.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>76.05</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>0.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.00</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-16T09:50:31.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
         </ns2:orderLines>
      </ns2:order>
      <ns2:order>
         <ns2:purchaseOrderId>1000018596</ns2:purchaseOrderId>
         <ns2:customerOrderId>5591500903533</ns2:customerOrderId>
         <ns2:customerEmailId>walsim-dev+-xvo_8j5fyi@cognitect.com</ns2:customerEmailId>
         <ns2:orderDate>2015-10-15T21:32:55.000Z</ns2:orderDate>
         <ns2:shippingInfo>
            <ns2:phone>(919) 555-1212</ns2:phone>
            <ns2:estimatedDeliveryDate>2015-10-16T06:59:59.000Z</ns2:estimatedDeliveryDate>
            <ns2:methodCode>Standard</ns2:methodCode>
            <ns2:postalAddress>
               <ns2:name>SimTest_Accept PGOMS</ns2:name>
               <ns2:address1>303 S Roxboro St.</ns2:address1>
               <ns2:address2>Suite 10</ns2:address2>
               <ns2:city>Durham</ns2:city>
               <ns2:state>NC</ns2:state>
               <ns2:postalCode>27701</ns2:postalCode>
               <ns2:country>USA</ns2:country>
               <ns2:addressType>OFFICE</ns2:addressType>
            </ns2:postalAddress>
         </ns2:shippingInfo>
         <ns2:orderLines>
            <ns2:orderLine>
               <ns2:lineNumber>1</ns2:lineNumber>
               <ns2:item>
                  <ns2:productName>The Bowflex Classic C10 Heart Rate Monitor Watch</ns2:productName>
                  <ns2:sku>BOW1020_6096338</ns2:sku>
               </ns2:item>
               <ns2:charges>
                  <ns2:charge>
                     <ns2:chargeType>PRODUCT</ns2:chargeType>
                     <ns2:chargeName>ItemPrice</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>45.00</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>ItemPrice</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>3.38</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
                  <ns2:charge>
                     <ns2:chargeType>SHIPPING</ns2:chargeType>
                     <ns2:chargeName>Shipping</ns2:chargeName>
                     <ns2:chargeAmount>
                        <ns2:currency>USD</ns2:currency>
                        <ns2:amount>4.99</ns2:amount>
                     </ns2:chargeAmount>
                     <ns2:tax>
                        <ns2:taxName>Shipping</ns2:taxName>
                        <ns2:taxAmount>
                           <ns2:currency>USD</ns2:currency>
                           <ns2:amount>0.37</ns2:amount>
                        </ns2:taxAmount>
                     </ns2:tax>
                  </ns2:charge>
               </ns2:charges>
               <ns2:orderLineQuantity>
                  <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                  <ns2:amount>1</ns2:amount>
               </ns2:orderLineQuantity>
               <ns2:statusDate>2015-10-15T14:50:32.000Z</ns2:statusDate>
               <ns2:orderLineStatuses>
                  <ns2:orderLineStatus>
                     <ns2:status>Created</ns2:status>
                     <ns2:statusQuantity>
                        <ns2:unitOfMeasurement>EACH</ns2:unitOfMeasurement>
                        <ns2:amount>1</ns2:amount>
                     </ns2:statusQuantity>
                  </ns2:orderLineStatus>
               </ns2:orderLineStatuses>
            </ns2:orderLine>
         </ns2:orderLines>
      </ns2:order>
   </ns2:elements>
</ns2:list>';

$xmlParser->parseXMLString($string);

var_dump($xmlParser);

